config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registration, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/information' => 'customers#update'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true
  validates :postage, presence: true
  validates :price, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1, making: 2, ready: 3, complete: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    order_details = order.order_details
    if order.order_status == "confirmation"
      order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end



end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row m-5">
    <h5><span class="bg-light">注文履歴詳細</span></h5>
  </div>

  <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
  <table class="table table-borderless" style="width:100%">
    <tr>
      <th style="width:10em">購入者</th>
      <td style="width:10em">
        <%= link_to admin_customer_path(@order.customer.id), class: "text-dark" do %>
          <u><%= @order.customer.full_name %></u>
        <% end %>
      </td>
      <td></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td colspan="2">〒<%= @order.postal_code %> <%= @order.address %><br>
      <%= @order.name %></td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td><%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, {}, {class: 'form-control form-control-sm text-center'} %></td>
      <td><%= f.submit "更新", class: "btn btn-success btn-sm" %></td>
    </tr>
  </table>
  <% end %>

  <div class="row">
    <div class="col-7">

      <table class="table">
        <thead class="bg-light text-nowrap">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th style="width:10em">製作ステータス</th>
          <th style="width:3em"></th>
        </thead>
        <tbody class="table-borderless">
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
            <td colspan="2" class="text-nowrap d-inline-block">
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, {}, {class: 'form-control form-control-sm text-center d-inline-block'} %>
                <%= f.submit "更新", class: "btn btn-success btn-sm mx-2" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
    <div class="col-4 align-self-end offset-1">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= (@order.price - @order.postage).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= @order.price.to_s(:delimited) %>円</th>
        </tr>
      </table>
    </div>
  </div>
</div>