config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registration, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/information' => 'customers#update'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + '　' + address + '　' + name
  end

  validates :name, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, inclusion: { in: 1..10 }

  def subtotal_intenger
    item.add_tax_intenger * amount
  end

  def subtotal
    subtotal_intenger.to_s(:delimited)
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :address, presence: true
  validates :telephone_number, length: {in: 10..11}, numericality: { only_integer: true }

  def full_name
    self.last_name + self.first_name
  end

  def address_display
    '〒' + postal_code + '　' + address
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  def add_tax_intenger
    (price * 1.1).floor
  end

  def add_tax_price
    add_tax_intenger.to_s(:delimited)
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true
  validates :postage, presence: true
  validates :price, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1, making: 2, ready: 3, complete: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { impossible: 0, waiting: 1, making: 2, complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :genre_id, :name ,:introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-light bg-white">
        <div class="container">
          <h3 class="navbar-brand text-nowrap">ながのCAKE</h3>

          <div>
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
          <% end %>
          </div>

          <div>
            <ul class="nav">
            <% if admin_signed_in? %>
              <li class="nav-link"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-light text-dark " %></li>
              <li class="nav-link"><%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light text-dark" %></li>

            <% elsif customer_signed_in? %>
              <li class="nav-link"><%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "商品一覧", items_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "カート", cart_items_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-light text-dark" %></li>

            <% else %>
              <li class="nav-link"><%= link_to "About", about_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "商品一覧", items_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-light text-dark" %></li>
              <li class="nav-link"><%= link_to "ログイン", customer_session_path, class: "btn btn-outline-light text-dark" %></li>
            <% end %>
            </ul>

            <div class="text-right">
            <%= form_with do |f| %>
              <%= f.text_field :serch, placeholder: "Search"%>
            <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer></footer>
  </body>
</html>